event_calendar/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

event_calendar/calendarapp/urls.py
from django.urls import path

from . import views
from .views import archivo

app_name = "calendarapp"


urlpatterns = [
    path("calender/", views.CalendarViewNew.as_view(), name="calendar"),
    path("calenders/", views.CalendarView.as_view(), name="calendars"),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
    path('upload/', archivo.upload_file, name='upload_file'),
    path('archivos-subidos/', archivo.archivos_subidos, name='archivos_subidos'),
    path('crear-asignacion/', archivo.agregar_asignacion, name='crear_asignacion'),
    path('visualizar/', archivo.visualizar, name='visualizar'),
    path('visualizar/ciclo/<int:id_carrera>/', archivo.obtener_Ciclo, name='v_ciclo'),
    path('visualizar/materia/<int:id>', archivo.obtener_Materia, name='v_materias'),
    path('visualizar/archivo/materia/<int:id>', archivo.obtenerArchivoM, name='v_archivoM'),
    path('Noticiacion/secretaria/', archivo.secreNoti, name='secreNoti'),
    path('Notificar/<int:id>', archivo.notificar, name='notificar'),
]   

event_calendar/eventcalendar/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import DashboardView


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
]

event_calendar/calendarapp/models/archivos.py
from django.db import models
from accounts.models import User
from datetime import datetime

class Carrera(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
            return "%s" % (self.nombre)    

class Ciclo(models.Model):
    numCiclo = models.IntegerField()
    def __str__(self):
            return "%s" % (self.numCiclo)  

class CarreraCiclo(models.Model):
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE, related_name="carrera_c")
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE, related_name="ciclo_m") 
    class Meta:
        unique_together = ['carrera', 'ciclo']
    
    def __str__(self):
            return "%s %s" % (self.carrera,
                    self.ciclo)



class Materia(models.Model):
    nombre = models.CharField(max_length=100)
    numCreditos = models.IntegerField()
    numHoras = models.IntegerField()
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE, related_name="materia_carrera")
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE, related_name="materia_ciclo")

    def __str__(self) :
        return "%s" % (self.nombre)

class Asignacion(models.Model):

    nombre = models.CharField(max_length=100)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE, related_name="asignacion_carrera")
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE, related_name="asignacion_ciclo")
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name="asignacion_materia")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_asignacion")
    fecha_inicial = models.DateTimeField()
    fecha_final = models.DateTimeField()
    descripcion = models.CharField(max_length= 200)

    def __str__(self):
            return "%s" % (self.nombre)
    

class Archivos(models.Model):
    
    archivo = models.FileField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_archivo")
    fecha_subida = models.DateTimeField(auto_now_add=True)
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name='archivo_materia', null=True)
    asignacion = models.ForeignKey(Asignacion, on_delete=models.CASCADE, related_name='archivo_asignacion')
    def __str__(self):
            return "%s %s %s" % (self.archivo,
                    self.user,
                    self.fecha_subida)
    

event_calendar/calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse

from calendarapp.models import EventAbstract
from accounts.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return running_events


class Event(EventAbstract):
    """ Event model """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

event_calendar/calendarapp/views/archivo.py
from django.shortcuts import render, redirect
from calendarapp.forms import ArchivoForm, AsignacionForm
from calendarapp.models.archivos import Archivos, Asignacion, Carrera, Ciclo, Materia, CarreraCiclo
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from calendarapp.models import Event
from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponseForbidden
from django.urls import reverse

def es_superusuario(user):
    return user.is_superuser

@login_required
def upload_file(request):
    if request.method == 'POST':
        form = ArchivoForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            archivo = form.cleaned_data['archivo']
            if archivo:
                nuevo_archivo = form.save(commit=False)
                nuevo_archivo.user = request.user
                nuevo_archivo.asignacion = form.cleaned_data['asignacion']  # Accede al valor del campo 'asignacion' del formulario
                nuevo_archivo.save()
            return redirect(request.path)
    else:
        form = ArchivoForm(user=request.user)
    return render(request, 'archivo.html', {'form': form})



@login_required    
def archivos_subidos(request):
    archivos = Archivos.objects.filter(user=request.user)
    return render(request, 'archivos_subidos.html', {'archivos': archivos})    

@login_required
@user_passes_test(es_superusuario, login_url=None)
def agregar_asignacion(request):
    if request.method == 'POST':
        form = AsignacionForm(request.POST)
        if form.is_valid():
            asignacion = form.save()

            # Obtener el usuario seleccionado en el formulario
            user = form.cleaned_data['user']
            event = Event(
                user=form.cleaned_data['user'],  # Asignar el usuario actual (requiere que el usuario esté autenticado)
                title=form.cleaned_data['nombre'],
                description=form.cleaned_data['descripcion'],
                start_time=form.cleaned_data['fecha_inicial'],
                end_time=form.cleaned_data['fecha_final']
            )

            # Guardar la instancia del modelo en la base de datos
            event.save()
            # Enviar el correo el   ectrónico
            send_mail(
                subject='Asignación exitosa',
                message=f'Hola {user.email}, se ha asignado la tarea "{asignacion.nombre}".\nFecha de inicio: {asignacion.fecha_inicial}.\nFecha de entrega: {asignacion.fecha_final}.\nDescripción: {asignacion.descripcion}',
                from_email='tu_correo@gmail.com',  # Coloca aquí tu correo desde el que enviarás los correos
                recipient_list=[user.email],
                fail_silently=False,
            )

            return redirect(request.path)  # Redirige a la vista que quieras después de guardar el formulario
    else:
        form = AsignacionForm()
        
    return render(request, 'agregar_asignacion.html', {'form': form})

@login_required
@user_passes_test(es_superusuario, login_url=None)
def visualizar(request):
    carrera = Carrera.objects.all()
    return render(request, 'visualizar.html', {'carreras': carrera})

@login_required
@user_passes_test(es_superusuario, login_url=None)
def obtener_Ciclo(request, id_carrera):
    try:
        carrera = Carrera.objects.get(pk=id_carrera)
        ciclos = CarreraCiclo.objects.filter(carrera=carrera)
    except Carrera.DoesNotExist:
        # Si la carrera no existe, puedes manejarlo como desees (por ejemplo, mostrar un mensaje de error).
        ciclos = []

    return render(request, 'v_ciclos.html', {'ciclos': ciclos, 'carreras': carrera})

@login_required
def obtener_Materia(request, id):
    try:
        ciclo = Ciclo.objects.get(pk=id)
        materias = Materia.objects.filter(ciclo=ciclo)
    except Ciclo.DoesNotExist:
        # Si el ciclo no existe, puedes manejarlo como desees (por ejemplo, mostrar un mensaje de error).
        materias = []

    return render(request, 'v_materias.html', {'ciclo': ciclo, 'materias': materias})

@login_required
@user_passes_test(es_superusuario, login_url=None)
def obtenerArchivoM(request, id):
    try:
        materia = Materia.objects.get(pk=id)
        archivos = Archivos.objects.filter(materia=materia)
    except Materia.DoesNotExist:
        # Si el ciclo no existe, puedes manejarlo como desees (por ejemplo, mostrar un mensaje de error).
        archivos = []

    return render(request, 'v_archivosM.html', {'materias': materia, 'archivos': archivos})

def secreNoti(request):
    asignacion = Asignacion.objects.all()
    diccionario = {'asignaciones': asignacion}
    return render(request, 'secreNoti.html', diccionario)


def notificar(request, id):
    asignacion = Asignacion.objects.get(pk=id)
    noti = asignacion.user
    send_mail(
                subject='Asignación exitosa',
                message=f'Por favor hacer la entrega del proyecto que se encuentra disponible hasta {asignacion.fecha_final}',
                from_email='tu_correo@gmail.com',  # Coloca aquí tu correo desde el que enviarás los correos
                recipient_list=[noti],
                fail_silently=False,
            )
    
    return redirect(reverse('calendarapp:visualizar'))

event_calendar/templates/add_member.html
{% extends 'base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendario </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Añadir </button></td></tr>
  </table>
</form>
{% endblock %}

event_calendar/templates/agregar_asignacion.html
{% extends "base.html" %}

{% block content %}
<html>
<head>
    <title>Crear asignación</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f2f2f2;
        }

        h2 {
            color: #33638B;
            text-align: center;
            margin-bottom: 20px;
        }

        form {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 4px;
        }

        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
            color: #333;
        }

        input[type="text"],
        input[type="file"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            resize: vertical;
            height: 100px;
        }

        button[type="submit"] {
            background-color: #33638B;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #20405e;
        }
    </style>
</head>
<body>
    <h2>Crear asignación</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
</body>
</html>
{% endblock %}

event_calendar/templates/archivo.html
{% extends "base.html" %}

{% block content %}
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
    }

    h2 {
      margin-bottom: 20px;
    }

    form {
      border: 2px solid #ccc;
      padding: 20px;
      max-width: 400px;
      margin: 0 auto;
    }

    label {
      display: block;
      margin-bottom: 10px;
    }

    input[type="file"] {
      display: block;
      margin-bottom: 10px;
    }

    button[type="submit"] {
      background-color: #4CAF50;
      color: #fff;
      padding: 10px 20px;
      border: none;
      cursor: pointer;
      font-size: 16px;
      border-radius: 4px;
    }

    button[type="submit"]:hover {
      background-color: #45a049;
    }
  </style>
<body>
  <h2>Subir archivo</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
</body>
</html>


{% endblock %}

event_calendar/templates/archivos_subidos.html
{% extends "base.html" %}

{% block content %}
<html>
<head>
    <title>Archivos Subidos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f2f2f2;
        }

        h1 {
            color: #33638B;
            text-align: center;
            margin-bottom: 20px;
        }

        .filters {
            margin-bottom: 20px;
        }

        h2 {
            color: #33638B;
            margin-top: 30px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        .archivo-row {
            display: table-row;
        }

        .archivo-row.hidden-row {
            display: none;
        }

        /* Estilos para hacer la tabla responsiva */
        .table-container {
            overflow-x: auto;
            max-width: 100%;
        }

        @media (max-width: 768px) {
            /* Estilos para pantallas más pequeñas (tabletas y móviles) */
            table {
                font-size: 14px;
            }

            .table-container {
                /* Para mejorar el desplazamiento horizontal en dispositivos móviles */
                -webkit-overflow-scrolling: touch;
                overflow-y: hidden;
            }
        }
    </style>
</head>
<body>
    <h1>Archivos Cargados</h1>

    <!-- Lista desplegable para filtrar por materia -->
    <div class="filters">
        <label for="materia">Filtrar por Materia:</label>
        <select id="materia">
            <option value="all">Todos</option>
            {% for archivo in archivos %}
                <option value="{{ archivo.materia.nombre }}">{{ archivo.materia.nombre }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="table-container">
        <table>
            <tr>
                <th>Nombre del Archivo</th>
                <th>Fecha de Subida</th>
                <th>Periodo</th>
                <th>Materia</th>
                <th>Carrera</th>
                <th>Opciones</th>
            </tr>
            {% for archivo in archivos %}
                <tr class="archivo-row" data-materia="{{ archivo.materia.nombre }}">
                    <td>{{ archivo.archivo.name }}</td>
                    <td>{{ archivo.fecha_subida }}</td>
                    <td>Noviembre-Febrero 2024</td>
                    <td>{{ archivo.materia.nombre }}</td>
                    <td>{{ archivo.materia.carrera.nombre }}</td>
                    <td><a href="">Actualizar</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <h2>Descripción</h2>

    <script>
        // Función para filtrar los archivos según la materia seleccionada
        function filterFiles() {
            const selectedMateria = document.getElementById('materia').value;
            const archivoRows = document.getElementsByClassName('archivo-row');
            for (let row of archivoRows) {
                if (selectedMateria === 'all' || row.dataset.materia === selectedMateria) {
                    row.classList.remove('hidden-row');
                } else {
                    row.classList.add('hidden-row');
                }
            }
        }

        // Agregar un evento para actualizar la tabla cuando cambia la selección en la lista desplegable
        document.getElementById('materia').addEventListener('change', filterFiles);

        // Mostrar todos los archivos al cargar la página
        filterFiles();
    </script>
</body>
</html>
{% endblock %}

event_calendar/templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Bienvenido, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Cerrar Sesion</a>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Próximo mes >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Mes anterior </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + Nuevo evento </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

event_calendar/templates/event-details.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendario </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Editar Evento </a>
        </div>

        <div class="clearfix">
            <h3>Nombre del Evento: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Miembros de este evento</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Añadir miembro </a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Nombre</th>
                  <th>Usuario</th>
                  <th>Correo</th>
                  <th>Accion</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

event_calendar/templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendario </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Añadir </button></td></tr>
  </table>
</form>
{% endblock %}

event_calendar/templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>¿Está seguro de que desea eliminar este evento?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirmar</button>
    </form>
{% endblock content %}

event_calendar/templates/secreNoti.html
{% extends "base.html" %}
{% block extracss %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"> 
{% endblock extracss %}

{% block content %}

<table id="tabla_datos">

  <thead>
    <tr>
      <th>Usuario</th>
      <th>Asignación</th>
      <th>Carrera</th>
      <th>Ciclo</th>
      <th>Materia</th>
      <th>Opciones</th>
    </tr>
  </thead>

  {% for l in asignaciones %}
  <tr>
    <td>{{l.user}}</td>
    <td>{{l.nombre}}</td>
    <td>{{l.carrera}}</td>
    <td>{{l.ciclo}}</td>
    <td>{{l.materia}}</td>
    <td> <a href="{% url 'calendarapp:notificar' l.id %}">Notificar</a>
    </td>

  </tr>
  {% endfor %}
</table>

{% block extrascripts %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>      
<script type="text/javascript">
    $(document).ready( function () {
      $('#tabla_datos').DataTable();
    });
</script>
{% endblock extrascripts %}

{% endblock %}

event_calendar/templates/superusuario.html
<!DOCTYPE html>
<html>
<head>
    <title>Superusuario</title>
</head>
<body>
    {% if superusuario %}
        <h1>Superusuario:</h1>
        <p>Nombre de usuario: {{ superusuario.username }}</p>
        <p>Email: {{ superusuario.email }}</p>
    {% else %}
        <p>No se encontró superusuario.</p>
    {% endif %}
</body>
</html>     

event_calendar/templates/v_archivosM.html
{% extends "base.html" %}
{% block extracss %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 20px;
        background-color: #f2f2f2;
    }

    h1 {
        color: #33638B;
        text-align: center;
        margin-bottom: 20px;
    }

    .filters {
        margin-bottom: 20px;
    }

    h2 {
        color: #33638B;
        margin-top: 30px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }

    .archivo-row {
        display: table-row;
    }

    .archivo-row.hidden-row {
        display: none;
    }

    /* Estilos para hacer la tabla responsiva */
    .table-container {
        overflow-x: auto;
        max-width: 100%;
    }

    @media (max-width: 768px) {
        /* Estilos para pantallas más pequeñas (tabletas y móviles) */
        table {
            font-size: 14px;
        }

        .table-container {
            /* Para mejorar el desplazamiento horizontal en dispositivos móviles */
            -webkit-overflow-scrolling: touch;
            overflow-y: hidden;
        }
    }
</style>
{% endblock extracss %}
{% block content %}
<div>
    <h1>Estado de documentación</h1>
    {% if archivos %}
        <div class="table-container">
            <table>
                <tr>
                    <th>Nombre</th>
                    <th>Fecha Subida</th>
                    <th>Usuario</th>
                    <th>Materia</th>
                    <th>Periodo</th>
                    <th>Estado</th>
                </tr>
            
            {% for archivo in archivos %}
                <tr class="archivo-row">
                    <td>{{ archivo.archivo }}</td>
                    <td>{{archivo.fecha_subida}}</td>
                    <td>{{archivo.user}}</td>
                    <td>{{archivo.materia.nombre}}</td>
                    <th>Noviembre-Febrero 2024</th>
                    <th><i class="fa fa-battery-three-quarters" aria-hidden="true"></i></th>
                </tr>
                
            {% endfor %}
            </table>
        </div>

        
    {% else %}
        <p>No hay archivos asociadas a este materia.</p>
    {% endif %}
</div> 
{% endblock %}

event_calendar/templates/v_ciclos.html
{% extends "base.html" %}

{% block content %}
<div>
    <h1>Ciclos de la carrera: {{ carreras.nombre }}</h1>
    {% if ciclos %}
        <div class="container">
            {% for carrera_ciclo in ciclos %}
                <div class="carrera">
                    <a href="{% url 'calendarapp:v_materias' carrera_ciclo.id %}">Ciclo N° {{ carrera_ciclo.ciclo.numCiclo }}</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No hay ciclos asociados a esta carrera.</p>
    {% endif %}
</div> 
{% endblock %}

event_calendar/templates/v_materias.html
{% extends "base.html" %}

{% block content %}
<div>
    <h1>Materias del ciclo: {{ ciclo.numCiclo }}</h1>
    {% if materias %}
        <div class="container">
            {% for materia in materias %}
                <div class="carrera">
                    <a href="{% url 'calendarapp:v_archivoM' materia.id %}">{{ materia.nombre }}</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No hay materias asociadas a este ciclo.</p>
    {% endif %}
</div> 
{% endblock %}

event_calendar/templates/visualizar.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <div class="container"> <!-- Aplica la clase "container" al contenedor principal -->
        {% for e in carreras %}
            <div class="carrera"> <!-- Aplica la clase "carrera" al contenedor de cada carrera -->
                <a href="{% url 'calendarapp:v_ciclo' e.id %}">{{e.nombre}}</a>
            </div>
        {% endfor %}
    </div> 
    {% endblock %} 
</body>
</html>